with-expecter: true
packages:
  ps_crawler:
    config:
      all: true
      recursive: true
      inpackage: true
      outpkg: "mock_{{.PackageName}}"
      # dir: "{{.PackageName}}"
      dir: "{{.PackageName}}/mocks"

