version: "3.9"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-c ./auth.conf --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
    env_file: 
      - .env
    volumes:
      - ./auth.conf:/auth.conf:ro

networks:
  nats:
    name: nats