services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-c ./auth.conf --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
    env_file:
      - .env
    volumes:
      - ./auth.conf:/auth.conf:ro
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - ./postgres/pg_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5000:5000
    environment:
      - PGADMIN_DEFAULT_EMAIL=some@one.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5000

networks:
  nats:
    name: nats
